version: '3.9'

services:
  db:
    image: mysql
    ports:
      - 3307:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: go-fiber
      MYSQL_ROOT_PASSWORD: nsdgvjklosngojwsn

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8082:80
    environment:
      - PMA_ARBITRARY=1

  api:
    container_name: go-fiber-app
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - db
      - phpmyadmin

volumes:
  mysql-data:
    driver: local
